### ISSUE TITLE
Map resource zones with energy value (depends also on research level)

### ISSUE THREAD

**Issue by alv67** [AB-Normals/Lux-AI-challenge#14]

**Comment by gteti** [comment]
Is this meant for city tales or a generic map scanning to "know" where all resources are placed?

**Comment by alv67** [comment]
Create a map (board of width x height) where each cell has a number of resouce/energy that a unit can grab if placed in that cell.
Since a unit adiacent to a resource can grab resource from any adiacent cell, even in a cell with no resources can be a number of energy that came from neighborhood cells
