### ISSUE TITLE
Actions -> Move function: Is repeated code wanted ?

### ISSUE THREAD

**Issue by gteti** [AB-Normals/Lux-AI-challenge#21]
I was just checking #20 and saw the code for the move function. I've seen the repetition of the `pos = unit.pos.translate(dir, 1)` with the following IF. Is it something required to arrange a double movement or not ?

```python
def move(self, unit: Unit, dir) -> bool:
        pos = unit.pos.translate(dir, 1)            
        if self._isPosOk(pos, unit):
            self.next_pos[unit.id] = pos
            self.actions.append(unit.move(dir))
            return True
        dir = self._alternativeDirection(dir)
        pos = unit.pos.translate(dir, 1)
        if self._isPosOk(pos, unit):
            self.next_pos[unit.id] = pos
            self.actions.append(unit.move(dir))
            return True
        else:
            self.next_pos[unit.id] = unit.pos
            return False
```

Thanks

**Comment by alv67** [comment]
Is used if first movement has some impediment.
`self._isPosOk` return false if the movement is not possible for example for possible collision.
If it is that case then an `self._alternativeDirection` is calculated and new movement is programmed.
If even this second movement has impediment then the move return `False`

**Comment by gteti** [comment]
Thank you for explaining.
